### ISSUE TITLE
Misleading comment about Fetch

### ISSUE THREAD

**Issue by purrgrammer** [zio/zio-query#145]
Hi, Fetch author here, I no longer mantain the project but I have noticed that it is mentioned in the docs.

> Compared with Fetch, ZIO Query supports pipelining, supports response types that depend on request types, does not require higher-kinded types and implicits, supports ZIO environment and statically typed errors, and has no dependencies except for ZIO.

While most of these are true, Fetch does support pipelining although I called it "batching" (grouping requests to the same data source in a batch). I'm not a native speaker so your language might be more accurate but the statement is false, I hope you correct it.

Congrats on this project btw, using a powerful effect type like `ZIO` makes the library a lot more ergonomic. I considered making a version of Fetch with `ZIO` but I no longer do Scala, I'm glad someone did!

**Comment by adamgfraser** [comment]
@purrgrammer Thanks for your feedback! I just corrected it.
