### ISSUE TITLE
Implement some missing ZIO combinators

### ISSUE THREAD

**Issue by nbenns** [zio/zio-query#37]
Combinators we are used to in ZIO don't yet exist in ZQuery.

`ZQuery.access`
`ZQuery.accessM`

There are definitely more.

This is a ticket to these specific combinators and perhaps some more.

**Comment by adamgfraser** [comment]
Totally agree. So far I have tried to be a fast follower and just add combinators very quickly when anyone needs them but could be worth a more comprehensive effort to implement all the ZIO combinators that make sense so users have all the tools they are used to from ZIO when working with ZQuery. Will try to put together a comprehensive list that we can work through but if there are any particular ones you are looking for can add them immediately..

**Comment by ghostdogpr** [comment]
I recently had a need for `ensuring`. Someone on Discord was also looking for `someOrFail`.

**Comment by aappddeevv** [comment]
someOrFail would be helpful to me!

**Comment by adamgfraser** [comment]
@aappddeevv Just added `someOrFail` in #108.

`ensuring` will take a little more work since I think that will require changes to the underlying representation but will work on that.

If anyone has other operators that would be helpful to them please comment here and I will start a list.

**Comment by paulpdaniels** [comment]
@adamgfraser gonna take this on for the hackathon

**Comment by voidconductor** [comment]
@adamgfraser 
timeoutTo, timeoutFail and other timeout combinators would be immensely helpful!

**Comment by adamgfraser** [comment]
@voidconductor Will add!

**Comment by mikaelstaldal** [comment]
`ZQuery.collectAll(Option)` would be nice. I think it would be very easy to implement since there is already a `ZQuery.foreach(Option)`.

**Comment by adamgfraser** [comment]
@mikaelstaldal Will add!
