### ISSUE TITLE
Merge with zio-cache

### ISSUE THREAD

**Issue by regiskuckaertz** [zio/zio-query#378]
zio-cache and zio-query are a match made in heaven. With zio-query, you get the pipelining and batching but the cache is recreated on every run and has no eviction strategy. With zio-cache, you get all these good things but there is no batching.

Is there a world where we could give `run` a `Cache[k, e, v]` that would cross execution boundaries? It would be especially useful in streaming pipelines where you want to `mapM` each element by pulling data from another service.

**Comment by adamgfraser** [comment]
You can actually already share a cache across execution boundaries using `Query#runCache`.

**Comment by regiskuckaertz** [comment]
Ha thank you, I had missed that. There is so much overlap between the two, it still feels like there is an opportunity there, though zio-cache seems more like an aspect you would put over a `DataSource`.
