### ISSUE TITLE
`ZQuery.fromZIO` never applies DataSourceAspects

### ISSUE THREAD

**Issue by frekw** [zio/zio-query#416]
This bit me today when implementing a tracing wrapper for Caliban.

It seems like `DataSourceAspect`s are never executed for ZQueries created via `ZQuery.fromZIO`, [scastie here](https://scastie.scala-lang.org/kpyGzQBgSly0DvRLibhVXQ).

As a caller, this feels a inconsistent since I don't really have a way of knowing how the ZQuery was constructed, and it also means that currently isn't really a way to implement an aspect for ZQueries in the general sense.

I think it's due to the combination of how [`ZQuery.fromZIO`](https://github.com/zio/zio-query/blob/series/2.x/zio-query/shared/src/main/scala/zio/query/ZQuery.scala#L1283) is implemented along with the behaviour of [`Result.done`](https://github.com/zio/zio-query/blob/series/2.x/zio-query/shared/src/main/scala/zio/query/internal/Result.scala#L40).

I wonder if an alternative implementation of `ZQuery.fromZIO` could be to still treat it as a `Result.Blocked` whose blocking requests are `BlockingRequests.empty` and have to continuation be the ZIO passed in? I guess it will incur some slight overhead but behave consistently.

**Comment by adamgfraser** [comment]
A `DataSourceAspect` transforms one `DataSource` into another so it is the wrong place to look for transforming a query that does not involve any `DataSource` at all. However, there could be a `QueryAspect` that is similar to a `ZIOAspect` that allows modifying a query more generally. I will take a look at this.

**Comment by frekw** [comment]
Awesome @adamgfraser! For reference, this is where I ran into it: https://github.com/ghostdogpr/caliban/pull/1616
