### ISSUE TITLE
foldCauseQuery doesn't catch defects that happen inside DataSource

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-query#433]
If I use `die` inside a `DataSource`, `foldCauseQuery` doesn't catch it.
If instead I do `ZQuery.fromZIO(ZIO.dieMessage("boom"))` it is caught as expected.

Reproducer: https://scastie.scala-lang.org/Y0CJr7ptSkeEUv9ENNDLfA

**Comment by adamgfraser** [comment]
Resolved by #434.
