### ISSUE TITLE
Bad memory consumption

### ISSUE THREAD

**Issue by melgenek** [zio/zio-query#58]
I bumped into a problem when zquery consumes a lot of memory and the execution does not finish.
 
I am using the zquery in the scenario like with 3 http calls:
- 1 call gets all Users
- 1 call gets all Addresses
- 1 call gets all Payment methods
Each of the requests succeeds separately.

The DataSource's are created for Addresses and Payment methods. For each user, I am trying to get the Address and a Payment method.
For a small number of entities the code works, the big amount of entities causes several gigabytes of memory to be consumed and the program never finishes.

There is a simple code to reproduce the problem without real http calls but a mocked http response https://github.com/melgenek/zquery-playground/blob/master/src/main/scala/Main.scala
The heap dump shows a significant amount of zio.Chunks, though I did not dig deep into the dump to see the whole picture.

**Comment by adamgfraser** [comment]
@melgenek Thanks for reporting! Will take a look and get back to you!

**Comment by adamgfraser** [comment]
@melgenek Just merged a fix and added your reproducer as a test case. Thank you for reporting! Would it be possible for you to confirm that this resolves your issue in production as well? I can also do a patch release if you need it.

**Comment by melgenek** [comment]
Thank you for the fast response. I tried it in my project against the snapshot. The query finishes now.

However, it is slower than the stupid implementation that I implemented when zquery did not work.
So my idea is to simply get several lists of data via http and compose them into the result like this
```
  val simpleResult = for {
    users <- Http.users
    addresses <- Http.addresses
    payments <- Http.payments
  } yield {
    val addressesMap = addresses.groupBy(_.id).view.mapValues(_.head)
    val paymentsMap = payments.groupBy(_.id).view.mapValues(_.head)
    users.map { user =>
      val payment = paymentsMap(user.paymentId)
      val address = addressesMap(user.addressId)
      (user, payment, address)
    }
  }
```
I updated the example to illustrate the zquery/non-zquery approaches https://github.com/melgenek/zquery-playground/blob/master/src/main/scala/Main.scala
A very basic time measurement says that zquery is 13 times slower on my machine then the custom results composition.

**Comment by adamgfraser** [comment]
Thanks for the feedback! I would expect that building up a query would be slower than a "naive" encoding if you aren't actually doing any optimizations in the data source since we have to do more work to build up this structure to determine what optimizations can be applied and then aren't actually doing any optimizations. But obviously would like the overhead to be much lower than that. Will spend some more time on it and get back to you. Thanks again for following up!
