### ISSUE TITLE
Cache has a private member but probably should not

### ISSUE THREAD

**Issue by aappddeevv** [zio/zio-query#96]
I was looking to implement my own Cache but noticed that Cache has a private member which I'm not sure should be there. Or at least, it's not clear that it should be the Cache trait since it has a `private[query]` modifier.

https://github.com/zio/zio-query/blob/e3452ec3f907e1a6f683becd8445b6ec44d58853/zio-query/shared/src/main/scala/zio/query/Cache.scala#L35

**Comment by aappddeevv** [comment]
I'm happy to submit a request but I saw that this function is used in ZQuery.fromRequest so I'm not sure if it should be really private or just part of the cache API.

**Comment by adamgfraser** [comment]
@aappddeevv Yes sorry for the delay on this. I think we need to do something to make this more extensible but also thinking through a bit what the best interface is. Let me get back to you on this tomorrow.
